repos:
  - repo: local
    hooks:
      - id: check
        name: check
        files: "^.rs"
        stages: [commit]
        language: system
        entry: cargo check
        types: [rust]

      - id: format
        name: format
        files: "^.rs"
        stages: [commit]
        language: system
        pass_filenames: true
        entry: cargo fmt -- --check
        types: [rust]

      - id: test
        name: test
        stages: [push]
        entry: cargo test
        pass_filenames: false
        language: system
        always_run: true
        types: [rust]
