repos:
  - repo: local
    hooks:
      - id: check
        name: check
        files: ".rs$"
        stages: [commit]
        language: system
        entry: cargo check
        types: [rust]
        pass_filenames: false

      - id: format
        name: format
        files: ".rs$"
        stages: [commit]
        language: system
        pass_filenames: true
        entry: cargo fmt -- --check
        types: [rust]

      - id: clippy
        name: clippy
        files: ".rs$"
        stages: [commit]
        language: system
        pass_filenames: false
        entry: >
          cargo clippy
            --all-targets
            --all-features

      - id: test
        name: test
        stages: [push]
        entry: cargo test --doc
        pass_filenames: false
        language: system
        always_run: true
        types: [rust]
