[package]
name = "rustore"
version = "0.1.0"
authors = ["Giuseppe Papallo <giuseppe@papallo.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.3"
clap = "2.33.0"
actix-web = "3"
actix-multipart = "0.3.0"
futures = "0.3.1"
sanitize-filename = "0.3.0"
serde = "1.0.125"
infer = { version = "0.4.0" }
tempfile = "3"
ignore = "0.4"