name: Publish to crates.io

on:
  push:
    branches:
      - $default-branch
    tags:
      - "lib-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Publish
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cd rstr/ && cargo publish --token $CRATES_IO_TOKEN
